name: Feature Request
description: Suggest a new feature or improvement to Certbot
title: "[Feature Request]: "
labels: ["feature request"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this feature solve or what does it enhance?
      description: Explain what this feature addresses, or the benefit it provides.
      placeholder: For example, "Currently, users have to manually do X, which is time-consuming."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: For example, "Implement a new button that automatically does X."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: For example, "We considered Y, but Z is a better approach because..."
  - type: dropdown
    id: area
    attributes:
      label: Relevant Area
      description: Which part of the project does this relate to?
      options:
        - label: acme
        - label: apache
        - label: cert management
        - label: code health
        - label: compatibility-test
        - label: csr
        - label: debian / ubuntu
        - label: dns
        - label: docker
        - label: documentation
        - label: error handling
        - label: fedora / redhat / CentOS
        - label: hooks
        - label: install
        - label: logging
        - label: macOS
        - label: manual authenticator
        - label: mypy
        - label: nginx
        - label: ocsp
        - label: performance
        - label: pkging
        - label: policy
        - label: pyca
        - label: python
        - label: refactoring
        - label: rename
        - label: renewal
        - label: security
        - label: snaps
        - label: spec-compliance
        - label: standalone
        - label: SUSE
        - label: testing
        - label: tooling
        - label: ui / ux
        - label: windows
        - label: 3rd party
