name: Merge Event

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Create Mattermost Message
      env: 
        NUMBER: ${{ github.event.number }}
        PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
      run: |
        echo "{\"text\":\"[${{ github.repository }}] | #[$NUMBER]($PR_URL) was merged into master by ${{ github.actor }}.\"}" > mattermost.json
    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_DAILY }}
