name: Weekly Github Update

on:
  schedule:
    # Every week on Thursday @ 1PM
    #- cron: "0 1 * * 4"
    - cron: "*/5 * * * *"
jobs:
  send-mattermost-message:
    runs-on: ubuntu-latest

    steps:
    - name: Create Mattermost Message
      run: |
        DATE=$(date  --date="7 days ago" +"%Y-%m-%d")
        MERGED_URL="https://github.com/pulls?q=merged%3A%3E${DATE}+org%3Acertbot+"
        UPDATED_URL="https://github.com/pulls?q=updated%3A%3E${DATE}+org%3Acertbot+"
        echo "{
                \"text\":\"## Updates Across Certbot Repos\n\n - Updated PRs in Past Week: [link]($UPDATED_URL)\n\n - Merged PRs in the Past Week: [link]($MERGED_URL)\n\n - Want to Discuss something today? Place it [here](https://docs.google.com/document/d/17YMUbtC1yg6MfiTMwT8zVm9LmO-cuGVBom0qFn8XJBM/edit?usp=sharing) and we can meet today on Zoom. \"
              }" > mattermost.json
    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          
