name: Merge Event

on:
  push:
    branches:
      - master

jobs:
  on_merge:
    runs-on: ubuntu-latest
    steps:
    - name: Create Mattermost Message
      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      env: 
        NUMBER: ${{ github.event.after }}
        PR_URL: ${{ github.event.commits[0].url }}
        REPO: ${{ github.repository }}
        USER: ${{ github.actor }}
#         TITLE: ${{  }}
      run: |
        $NUMBER = $NUMBER | cut -c -7
        jq --null-input \
                --arg number "$NUMBER" \
                --arg pr_url "$PR_URL" \
                --arg repo "$REPO" \
                --arg user "$USER" \
                --arg title "$TITLE" \
        '{ "text": "[\($repo)] | #\($number) was merged into master by \($user)" }' > mattermost.json
    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_DAILY }}
