name: Weekly Github Update

on:
  push:
  #schedule:
    # Every week on Thursday @ 1PM
    # - cron: "0 1 * * 4"
    #- cron: "*/5 * * * *" #Test Cron
jobs:
  send-mattermost-message:
    runs-on: ubuntu-latest
    env:
        DATE: $(date  --date="7 days ago" +"%Y-%m-%d")
        MERGED_URL: "https://github.com/pulls?q=merged%3A%3E${DATE}+org%3Acertbot+"
        UPDATED_URL: "https://github.com/pulls?q=updated%3A%3E${DATE}+org%3Acertbot+"
    steps:
      - uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          PAYLOAD: |-
            {
              "text": "Updates Across Certbot Repos:
                - Certbot team members SHOULD look at: $MERGED_URL and MAY also want to look at: [link]($UPDATED_URL),
                - The key words SHOULD and MAY in this message are to be interpreted as described in [RFC 8147](https://www.rfc-editor.org/rfc/rfc8174).",
              "channel": "private certbot",
              "username": "${{ github.triggering_actor }}",
              "icon": "https://cdn3.iconfinder.com/data/icons/system-basic-vol-4-1/20/icon-note-attention-alt3-512.png"
            }
